team-web-development-projects/developer-talks-backend

src/main/java/com/dtalks/dtalks/user/service/UserServiceImpl.java
src/test/java/com/dtalks/dtalks/user/service/UserServiceImplTest.java

signUp 테스트 코드 추가했습니다.
signIn 테스트 코드 추가를 위해선 signIn 메서드의 리턴값을 바꿔줄 필요가 있어 추후 수정이후 테스트 코드 작성을 해야 할것같습니다.

feat: 테스트코드 추가

---

src/main/java/com/dtalks/dtalks/board/post/controller/PostController.java
src/main/java/com/dtalks/dtalks/board/post/dto/PostDto.java
src/main/java/com/dtalks/dtalks/board/post/dto/PostRequestDto.java
src/main/java/com/dtalks/dtalks/board/post/entity/Post.java
src/main/java/com/dtalks/dtalks/board/post/repository/PostRepository.java
src/main/java/com/dtalks/dtalks/board/post/service/PostService.java
src/main/java/com/dtalks/dtalks/board/post/service/PostServiceImpl.java

다른 기능 수정은 없이 borad 폴더 추가 후에 post 폴더를 board 폴더 안으로 옮겼습니다.
dtalks.post -> dtalks.board.post

fix: post 폴더 위치 변경

---

src/main/java/com/dtalks/dtalks/user/config/JwtTokenProvider.java
src/main/java/com/dtalks/dtalks/user/config/OAuthSuccessHandler.java
src/main/java/com/dtalks/dtalks/user/dto/UserTokenDto.java
src/main/java/com/dtalks/dtalks/user/entity/User.java
src/main/java/com/dtalks/dtalks/user/enums/OAuthAttributes.java
src/main/java/com/dtalks/dtalks/user/service/OAuthServiceImpl.java
src/main/java/com/dtalks/dtalks/user/service/UserServiceImpl.java

sub -> email
userid -> oauth의 경우 email, 아니면 id
nickname -> oauth의 경우 기본값 name
ex)
eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJybGFkeWRnbjc1NzVAZ21haWwuY29tIiwidXNlcmlkIjoicmxhZHlkZ243NTc1QGdtYWlsLmNvbSIsIm5pY2tuYW1lIjoi7Ius7Ius7ZWg65WQ7L2U65SpIiwiaWF0IjoxNjgzMDk0Njk1LCJleHAiOjE2ODMxMDU0OTV9.OSTE7nn6LUDUeVegKt7XzYWK74sfHYblmw379hpqCwI

fix: 토큰 안에 들어가는 값 추가

---

src/main/java/com/dtalks/dtalks/exception/GlobalExceptionHandler.java
src/main/java/com/dtalks/dtalks/user/entity/User.java

GlobalExeptionHandlermerge 충돌부분 해결
User post import 경로 충돌 해결

fix:GlobalExeption_merge 충돌 해결

---

build.gradle
src/main/java/com/dtalks/dtalks/user/config/SecurityConfiguration.java
src/main/java/com/dtalks/dtalks/user/controller/SignController.java
src/main/java/com/dtalks/dtalks/user/controller/UserController.java
src/main/java/com/dtalks/dtalks/user/dto/SignInResponseDto.java
src/main/java/com/dtalks/dtalks/user/service/TokenService.java
src/main/java/com/dtalks/dtalks/user/service/TokenServiceImpl.java
src/main/java/com/dtalks/dtalks/user/service/UserService.java
src/main/java/com/dtalks/dtalks/user/service/UserServiceImpl.java

url user -> users 복수형으로 변경했습니다.
refresh 토큰이 추가되었습니다.

feat: refresh 토큰, refresh 토큰을 이용한 토큰 재발급 기능 추가

---

src/main/java/com/dtalks/dtalks/qna/answer/controller/AnswerController.java
src/main/java/com/dtalks/dtalks/qna/answer/dto/AnswerDto.java
src/main/java/com/dtalks/dtalks/qna/answer/dto/AnswerResponseDto.java
src/main/java/com/dtalks/dtalks/qna/answer/entity/Answer.java
src/main/java/com/dtalks/dtalks/qna/answer/repository/AnswerRepository.java
src/main/java/com/dtalks/dtalks/qna/answer/service/AnswerService.java
src/main/java/com/dtalks/dtalks/qna/answer/service/AnswerServiceImpl.java
src/main/java/com/dtalks/dtalks/qna/question/controller/QuestionController.java
src/main/java/com/dtalks/dtalks/qna/question/dto/QuestionDto.java
src/main/java/com/dtalks/dtalks/qna/question/dto/QuestionResponseDto.java
src/main/java/com/dtalks/dtalks/qna/question/entity/Question.java
src/main/java/com/dtalks/dtalks/qna/question/repository/QuestionRepository.java
src/main/java/com/dtalks/dtalks/qna/question/service/QuestionService.java
src/main/java/com/dtalks/dtalks/qna/question/service/QuestionServiceImpl.java
src/main/java/com/dtalks/dtalks/user/entity/User.java

chore:question, answer를 qna폴더에 합침

chore:question, answer 폴더 합침

---

src/main/java/com/dtalks/dtalks/board/comment/controller/CommentController.java
src/main/java/com/dtalks/dtalks/board/comment/service/CommentServiceImpl.java
src/main/java/com/dtalks/dtalks/board/post/controller/PostController.java

1. 댓글 수정 변수 이름 변경 (postId -> id). 변수 이름이 댓글 id에서 게시글 id로 잘못 작성되어있음
2. post controller, comment controller에 swagger에 표시되는 설명 추가

Feat:comment,swagger

---

src/main/java/com/dtalks/dtalks/board/post/controller/PostController.java
src/main/java/com/dtalks/dtalks/board/post/repository/PostRepository.java
src/main/java/com/dtalks/dtalks/board/post/service/PostService.java
src/main/java/com/dtalks/dtalks/board/post/service/PostServiceImpl.java
src/main/java/com/dtalks/dtalks/user/config/SecurityConfiguration.java

1. securityConfiguration: 게시글, 댓글 조회 기능은 로그인 없이 접근 할 수 있도록 변경
2. 게시글 검색 기능 추가
3. 사용자의 게시글 조회를 기존 리스트에서 페이지로 가져오도록 변경

Feat:post 게시글 검색 기능, securityconfig에 post, comment GET API 접근 변경

---

src/main/java/com/dtalks/dtalks/user/Util/SecurityUtil.java

유저 권한체크는 많은 곳에서 기본적으로 사용되기 때문에 유틸에 추가했습니다.

fix: 유저 권한체크 유틸 추가

---

src/main/java/com/dtalks/dtalks/board/comment/controller/CommentController.java
src/main/java/com/dtalks/dtalks/board/comment/dto/CommentInfoDto.java
src/main/java/com/dtalks/dtalks/board/comment/dto/CommentRequestDto.java
src/main/java/com/dtalks/dtalks/board/post/controller/PostController.java
src/main/java/com/dtalks/dtalks/board/post/dto/FavoriteAndRecommendStatusDto.java
src/main/java/com/dtalks/dtalks/board/post/dto/PostDto.java

1. dto에 @Schema로 설명 추가
2. controller에 parameter 설명 추가

feat: post, comment에 대한 swagger 설명 추가

---

src/main/java/com/dtalks/dtalks/user/controller/SignController.java
src/main/java/com/dtalks/dtalks/user/controller/UserController.java
src/main/java/com/dtalks/dtalks/user/dto/SignUpDto.java
src/main/java/com/dtalks/dtalks/user/dto/UserResponseDto.java
src/main/java/com/dtalks/dtalks/user/entity/User.java
src/main/java/com/dtalks/dtalks/user/service/UserService.java
src/main/java/com/dtalks/dtalks/user/service/UserServiceImpl.java

유저 정보에 내소개글, 내 기술스택 추가 (회원가입시 입력받음)
로그인, 회원가입 swagger 설명 추가

fix: 유저정보에 내소개, 기술스택 추가

---

src/main/java/com/dtalks/dtalks/studyroom/controller/StudyRoomController.java
src/main/java/com/dtalks/dtalks/studyroom/entity/StudyRoom.java
src/main/java/com/dtalks/dtalks/studyroom/service/StudyRoomService.java
src/main/java/com/dtalks/dtalks/studyroom/service/StudyRoomServiceImpl.java

스터디룸 가입신청 api 입니다.
db 조회 더 좋은 방법 있다면 말씀 부탁드립니다.

feat: 스터디룸 가입신청

---

src/main/java/com/dtalks/dtalks/studyroom/controller/StudyRoomController.java
src/main/java/com/dtalks/dtalks/studyroom/dto/StudyRoomJoinResponseDto.java
src/main/java/com/dtalks/dtalks/studyroom/repository/StudyRoomUserRepository.java
src/main/java/com/dtalks/dtalks/studyroom/service/StudyRoomService.java
src/main/java/com/dtalks/dtalks/studyroom/service/StudyRoomServiceImpl.java

해당 유저가 가입중인 스터디룸에서 방장, 부방장인 경우에 모든 가입 신청 리스트 api
스터디룸 가입 승인 api 입니다.

feat: 스터디룸 가입신청 리스트, 가입승인 api

---

src/main/java/com/dtalks/dtalks/studyroom/controller/StudyRoomController.java
src/main/java/com/dtalks/dtalks/studyroom/entity/StudyRoom.java
src/main/java/com/dtalks/dtalks/studyroom/service/StudyRoomService.java
src/main/java/com/dtalks/dtalks/studyroom/service/StudyRoomServiceImpl.java
src/main/java/com/dtalks/dtalks/user/controller/UserController.java
src/main/java/com/dtalks/dtalks/user/dto/OAuthSignUpDto.java
src/main/java/com/dtalks/dtalks/user/service/UserService.java
src/main/java/com/dtalks/dtalks/user/service/UserServiceImpl.java

- 스터디룸 탈퇴 api
- 이메일 중복확인 api
- oauth/sign-up 리턴 값 오류 수정, profileImageId 잘못된 값 들어올 경우 그냥 무시하도록 변경

fix: 버그 수정, 스터디룸 탈퇴, 이메일 중복확인

---

src/main/java/com/dtalks/dtalks/qna/answer/controller/AnswerController.java
src/main/java/com/dtalks/dtalks/qna/answer/service/AnswerService.java
src/main/java/com/dtalks/dtalks/qna/answer/service/AnswerServiceImpl.java
src/main/java/com/dtalks/dtalks/qna/question/service/QuestionServiceImpl.java

- 채택 취소 api 삭제
- 채택된 답변 삭제 불가: 채택된 답변 삭제 시도시 '채택된 답변 삭제 불가' error code 발생

fix:채택 취소 api 삭제, 채택된 답변 삭제 불가

---

src/main/java/com/dtalks/dtalks/board/comment/service/CommentServiceImpl.java
src/main/java/com/dtalks/dtalks/board/post/service/FavoritePostServiceImpl.java
src/main/java/com/dtalks/dtalks/board/post/service/PostServiceImpl.java
src/main/java/com/dtalks/dtalks/qna/question/service/QuestionServiceImpl.java
src/main/java/com/dtalks/dtalks/studyroom/service/StudyRoomServiceImpl.java
src/main/java/com/dtalks/dtalks/user/repository/UserRepository.java
src/main/java/com/dtalks/dtalks/user/service/OAuthServiceImpl.java
src/main/java/com/dtalks/dtalks/user/service/UserDetailsServiceImpl.java
src/main/java/com/dtalks/dtalks/user/service/UserServiceImpl.java

1. 기존 userRepository.get~을 .find로 찾도록 변경
2. db에서 조회후에 없으면 throw하던 것들을 따로 처리

fix: userRepository.get~ -> find로 변경, 단순 조회 에러처리 메소드로 뺌

---

src/main/java/com/dtalks/dtalks/exception/GlobalExceptionHandler.java
src/main/java/com/dtalks/dtalks/user/controller/UserController.java
src/main/java/com/dtalks/dtalks/user/dto/UserEmailDto.java
src/main/java/com/dtalks/dtalks/user/dto/UserPasswordDto.java
src/main/java/com/dtalks/dtalks/user/dto/UseridDto.java
src/main/java/com/dtalks/dtalks/user/service/UserService.java
src/main/java/com/dtalks/dtalks/user/service/UserServiceImpl.java

- 유저 아이디 변경 api
- 유저 이메일 변경 api
- 유저 비밀번호 변경 api
- valid 에러시 에러 메세지 출력하도록 변경

feat: 유저 정보 수정 api

---

src/main/java/com/dtalks/dtalks/user/Util/SecurityUtil.java
src/main/java/com/dtalks/dtalks/user/service/UserServiceImpl.java

userRepository.save로는 너무 많은 조회 쿼리가 나가서 그냥 security util의 정보로 다시 한 번만 조회한 후에 set으로 update 처리만 해주는 편이 더 나음

fix: 사용자 비공개 설정 수정

---

src/main/java/com/dtalks/dtalks/exception/dto/ErrorResponseDto.java
src/main/java/com/dtalks/dtalks/studyroom/config/WebSocketConfiguration.java
src/main/java/com/dtalks/dtalks/studyroom/controller/ChatController.java
src/main/java/com/dtalks/dtalks/studyroom/dto/ChatMessageRequestDto.java
src/main/java/com/dtalks/dtalks/studyroom/handler/StompHandler.java
src/main/java/com/dtalks/dtalks/user/config/JwtAuthenticationFilter.java
src/main/java/com/dtalks/dtalks/user/config/SecurityConfiguration.java

- 소켓 통신 헤더에 jwt값이 안담기는 문제가 있습니다.
- 로그 출력 추가했습니다.
- 소켓 통신 jwt 인증 문제 때문에 현재 소켓통신은 security에서 열어뒀습니다.
- 소켓 통신 jwt 처리하는 코드는 작성하였습니다.

fix: 로그 추가, 소켓 통신 jwt 처리

---

src/main/java/com/dtalks/dtalks/board/post/dto/NewImageDto.java
src/main/java/com/dtalks/dtalks/board/post/dto/OldImageDto.java
src/main/java/com/dtalks/dtalks/board/post/dto/PutRequestDto.java
src/main/java/com/dtalks/dtalks/board/post/entity/PostImage.java
src/main/java/com/dtalks/dtalks/board/post/repository/PostImageRepository.java
src/main/java/com/dtalks/dtalks/board/post/service/PostServiceImpl.java

feat: 게시글 이미지 정렬 순서 추가

---

src/main/java/com/dtalks/dtalks/board/comment/service/CommentServiceImpl.java
src/main/java/com/dtalks/dtalks/qna/answer/service/AnswerServiceImpl.java
src/main/java/com/dtalks/dtalks/studyroom/service/StudyRoomServiceImpl.java

fix: 알림 메시지에 닉네임 추가

---

src/main/java/com/dtalks/dtalks/message/service/MessageServiceImpl.java
src/main/java/com/dtalks/dtalks/qna/answer/dto/AnswerResponseDto.java
src/main/java/com/dtalks/dtalks/qna/question/controller/QuestionController.java
src/main/java/com/dtalks/dtalks/qna/question/dto/QuestionResponseDto.java
src/main/java/com/dtalks/dtalks/qna/question/repository/ScrapQuestionRepository.java
src/main/java/com/dtalks/dtalks/qna/question/service/QuestionServiceImpl.java
src/main/java/com/dtalks/dtalks/qna/question/service/ScrapQuestionService.java
src/main/java/com/dtalks/dtalks/qna/question/service/ScrapQuestionServiceImpl.java
src/main/java/com/dtalks/dtalks/qna/recommendation/repository/RecommendQuestionRepository.java
src/main/java/com/dtalks/dtalks/qna/recommendation/service/RecommendQuestionService.java
src/main/java/com/dtalks/dtalks/qna/recommendation/service/RecommendQuestionServiceImpl.java

1. 메시지 내용 -> 메시지 발신자 변경
2. /post/check/status/{postId} api 추가
3. answerCount 변수이름을 commentCount로 변경
4. /answers/list/question/{questionId} api에서 userInfo 추가
5. 전체 질문글 조회 페이지 정렬 수정

Fix: Message 알림, Question 버그 수정

---

src/main/java/com/dtalks/dtalks/board/comment/service/CommentServiceImpl.java
src/main/java/com/dtalks/dtalks/board/post/service/RecommendPostServiceImpl.java
src/main/java/com/dtalks/dtalks/notification/repository/NotificationRepository.java
src/main/java/com/dtalks/dtalks/qna/answer/service/AnswerServiceImpl.java
src/main/java/com/dtalks/dtalks/qna/recommendation/service/RecommendQuestionServiceImpl.java
src/main/java/com/dtalks/dtalks/user/service/UserServiceImpl.java

게시글 추천, 댓글, 대댓글, 질문글 추천, 답변 작성됨, 답변 채택됨 알림이 탈퇴한 회원이지 않을 경우에만 가도록 수정
회원 탈퇴 시에 알림 삭제
회원 탈퇴 닉네임 null로 변경

Fix:회원탈퇴 시 알림 삭제, 탈퇴한 회원에게 알림 안 가도록 수정

---

src/main/java/com/dtalks/dtalks/notification/controller/NotificationController.java

fix: sse header에 X-Accel-Buffering 설정 추가

---

src/main/java/com/dtalks/dtalks/qna/answer/service/AnswerServiceImpl.java

1. 질문 작성자로 로그인해도 채택 안되는 버그 수정
2. findAnswer 메서드로 통일

Fix/답변 채택 질문자 채택 불가 버그 수정

---

src/main/java/com/dtalks/dtalks/qna/answer/dto/AnswerResponseDto.java
src/main/java/com/dtalks/dtalks/qna/answer/service/AnswerServiceImpl.java
src/main/java/com/dtalks/dtalks/qna/question/controller/QuestionController.java
src/main/java/com/dtalks/dtalks/qna/question/dto/QuestionResponseDto.java
src/main/java/com/dtalks/dtalks/qna/question/entity/Question.java

답변 응답 Dto 채택 여부 추가
질문 채택한 답변 여부 필드값 추가
질문자는 하나의 답변만 채택 가능
프론트 요청으로 스크랩 관련 api명 scrap -> favorite 으로 변경

Fix:QnA api 수정

---

src/main/java/com/dtalks/dtalks/admin/report/controller/AdminReportController.java
src/main/java/com/dtalks/dtalks/admin/report/dto/ReportedUserDto.java
src/main/java/com/dtalks/dtalks/admin/report/dto/ReportedUserInfoDto.java
src/main/java/com/dtalks/dtalks/admin/user/controller/AdminUserController.java
src/main/java/com/dtalks/dtalks/admin/user/dto/UserInfoChangeRequestDto.java
src/main/java/com/dtalks/dtalks/admin/user/dto/UserManageDto.java
src/main/java/com/dtalks/dtalks/admin/user/service/UserManageService.java
src/main/java/com/dtalks/dtalks/admin/user/service/UserManageServiceImpl.java
src/main/java/com/dtalks/dtalks/base/service/Schedule.java
src/main/java/com/dtalks/dtalks/report/controller/ReportController.java
src/main/java/com/dtalks/dtalks/user/config/SecurityConfiguration.java
src/main/java/com/dtalks/dtalks/user/repository/UserRepository.java

feat:admin 일시 정지 계정 ACTIVE로 변경하는 스케줄 등록, 회원 조회 필터 추가, 회원 정보 수정, 임시 비밀번호 발급

---

src/main/java/com/dtalks/dtalks/admin/user/controller/AdminUserController.java
src/main/java/com/dtalks/dtalks/admin/user/dto/UserManageDto.java
src/main/java/com/dtalks/dtalks/admin/user/service/UserManageService.java
src/main/java/com/dtalks/dtalks/admin/user/service/UserManageServiceImpl.java
src/main/java/com/dtalks/dtalks/user/config/SecurityConfiguration.java
src/main/java/com/dtalks/dtalks/user/controller/SignController.java
src/main/java/com/dtalks/dtalks/user/service/UserService.java
src/main/java/com/dtalks/dtalks/user/service/UserServiceImpl.java

/admin/sign-in 제외한 /admin/** 요청은 db에 ROLE_ADMIN으로 설정된 사용자만 관리자 작업 가능하도록 수정

feat:admin 관리자 로그인, 인증 작업 추가, update:admin 회원 조회 시 프로필 이미지 조회

---

src/main/java/com/dtalks/dtalks/admin/visitor/controller/VisitorController.java
src/main/java/com/dtalks/dtalks/admin/visitor/service/VisitorServiceImpl.java
src/main/java/com/dtalks/dtalks/user/config/SecurityConfiguration.java

- admin/visitors/increase -> /visitors/increase으로 변경
- 방문자수 조회 관리자 권한 추가
- /visitors/increase api security 변경

Fix: 방문자수 증가 api 명 변경, 방문자수 조회 관리자 권한 추가

---

src/main/java/com/dtalks/dtalks/message/controller/MessageController.java
src/main/java/com/dtalks/dtalks/message/repository/MessageRepository.java
src/main/java/com/dtalks/dtalks/message/service/MessageService.java
src/main/java/com/dtalks/dtalks/message/service/MessageServiceImpl.java

- 쪽지 id로 조회 -> 수신자 닉네임으로 쪽지 조회, 보낸 쪽지 에러 status 변경
- 쪽지 알람 수정: User로 넘기던거 nickname으로 수정, message.properties message 부분 수정

Fix: Message

---

src/main/java/com/dtalks/dtalks/admin/report/dto/ReportedPostDto.java
src/main/java/com/dtalks/dtalks/board/post/repository/PostRepository.java
src/main/java/com/dtalks/dtalks/board/post/service/PostServiceImpl.java
src/main/java/com/dtalks/dtalks/report/repository/CustomReportRepository.java
src/main/java/com/dtalks/dtalks/report/repository/ReportedPostRepository.java

exists문이 생각대로 작동하지 않고 이미 처리된 작업까지 가져오는 걸 발견. 조인이 발생할 수 밖에 없으니 그냥 innerJoin에서 조건으로 설정하고 distinct로 대체

fix:admin 신고된 사용자,게시글 조회 sql / fix: 게시글 검색 sql 수정
