src/main/java/com/dtalks/dtalks/board/post/controller/PostController.java, src/main/java/com/dtalks/dtalks/board/post/dto/PostDto.java, src/main/java/com/dtalks/dtalks/board/post/entity/Post.java, src/main/java/com/dtalks/dtalks/board/post/repository/PostRepository.java, src/main/java/com/dtalks/dtalks/board/post/service/PostService.java, src/main/java/com/dtalks/dtalks/board/post/service/PostServiceImpl.java
1. 게시글에서 생성 날짜, 수정 날짜 보이도록 dto 수정
2. 게시글에서 조회수가 보이도록 dto 수정, 조회수 업데이트 api 추가 (update하려는 post id 필요) http://localhost:8081 **/post/view/1**
3. 사용자의 게시글 리스트 조회 기능 추가 http://localhost:8081 **/post/list/user/1**  (조회하려는 사용자의 id (primary key) 필요, 추후 primary key가 아닌 nickname이나 다른 값으로 조회할거면 변경 가능)
=> Feat:post 게시글 생성,날짜,조회수 보이게 추가 + 사용자의 게시글 조회 추가

.gitignore, build.gradle
**받기 전에 Gradle -> Tasks -> build -> clean 실행으로 폴더 없애고 진행**
querydsl 스프링 3.x버전에 맞춰 수정
src/main/generated 폴더에 Q파일들이 생성됨으로 gitignore에 폴더명 추가
=> fix: querydsl 배포 오류 수정 (스프링3.x버전), gitignore에 폴더 추가

src/main/java/com/dtalks/dtalks/board/post/controller/PostController.java, src/main/java/com/dtalks/dtalks/board/post/service/PostService.java, src/main/java/com/dtalks/dtalks/board/post/service/PostServiceImpl.java
사용자의 게시글 조회, 검색어로 게시글 검색, 베스트 5 게시글 조회에 빠진 transactional(readOnly = true) 추가
게시글 조회 api -> 조회수 업데이트 api로 작동되던걸 프론트분의 요청으로 게시글 조회 api에서 조회수 업데이트도 되도록 변경
=> fix:post 빠진 transactional추가, 게시글 조회수 업데이트 방식 변경

src/main/java/com/dtalks/dtalks/board/post/repository/PostRepository.java, src/main/java/com/dtalks/dtalks/board/post/service/PostServiceImpl.java, src/main/java/com/dtalks/dtalks/user/config/SecurityConfiguration.java
- 게시글 조회에서 db로 가져오는 명령어가 잘못 설정되어 있어 변경
- securityConfiguration의 인증이 필요 없는 패턴에서 삭제된 api인 /post/view/부분 삭제
=> fix:post 게시글 정렬 수정, securityConfig에서 사용하지 않는 패턴 삭제

src/main/java/com/dtalks/dtalks/board/post/repository/FavoritePostRepository.java, src/main/java/com/dtalks/dtalks/board/post/repository/RecommendPostRepository.java, src/main/java/com/dtalks/dtalks/board/post/service/PostServiceImpl.java
게시글 삭제시 두 테이블을 검사해서 있으면 삭제하고 게시글 삭제하는 로직 추가
=> fix:post 게시글 삭제시 즐겨찾기, 추천 테이블 검사

src/main/java/com/dtalks/dtalks/user/config/SecurityConfiguration.java, src/main/java/com/dtalks/dtalks/user/controller/UserController.java, src/main/java/com/dtalks/dtalks/user/dto/RecentActivityDto.java, src/main/java/com/dtalks/dtalks/user/entity/User.java, src/main/java/com/dtalks/dtalks/user/service/UserService.java, src/main/java/com/dtalks/dtalks/user/service/UserServiceImpl.java
1. User에 isPrivate 추가로 사용자 비공개 설정 추가
2. 회원가입때 user.setIsPrivate(false) 추가
3. 사용자 최근활동 조회 닉네임으로 하도록 변경 + 로그인하지 않아도 볼 수 있도록 SecurityConfig 수정
4. 비공개 여부로 최근활동 조회 가능한지 알 수 있는 api 추가 (/users/private/{id}). 이거 조회 후에 false이면 최근활동 조회 날리면 됨. 비공개 여부 조회도 인증 없이 가능
5. 비공개 여부 설정할 수 있는 api 추가 (/users/setting/private/{id}/{status}): status가 true이면 비공개 설정되는 것
=> Feat: 사용자 최근활동 비공개 설정 추가, 인증 없이 되도록 수정

src/main/java/com/dtalks/dtalks/studyroom/controller/StudyRoomController.java, src/main/java/com/dtalks/dtalks/studyroom/service/StudyRoomService.java, src/main/java/com/dtalks/dtalks/studyroom/service/StudyRoomServiceImpl.java
- 스터디룸 삭제시 본인 이외의 스터디룸 멤버가 남아있으면 삭제 불가능하게 변경
- 스터디룸 가입 요청 리스트 페이지로 변경
- 스터디룸원 추방 api
- 가입중인 스터디룸 조회 api
=> fix: 스터디룸 추방 api, 페이지 추가, 스터디룸삭제 수정

build.gradle, src/main/java/com/dtalks/dtalks/news/controller/NewsController.java, src/main/java/com/dtalks/dtalks/news/entity/News.java, src/main/java/com/dtalks/dtalks/news/entity/NewsCrawler.java, src/main/java/com/dtalks/dtalks/news/service/NewsService.java, src/main/java/com/dtalks/dtalks/news/service/NewsServiceImpl.java, src/main/java/com/dtalks/dtalks/user/config/SecurityConfiguration.java
get: /news: bloter.net 사이트의 IT 기업 섹션의 기사들을 클롤링 해온다. (제목, 내용, 작성자, 날짜, 이미지 주소, 링크) 반환
=> feat: news 기사 crawling 기능 추가

src/main/java/com/dtalks/dtalks/news/controller/NewsController.java, src/main/java/com/dtalks/dtalks/news/entity/News.java, src/main/java/com/dtalks/dtalks/news/entity/NewsCrawler.java, src/main/java/com/dtalks/dtalks/news/repository/NewsRepository.java, src/main/java/com/dtalks/dtalks/news/service/NewsService.java, src/main/java/com/dtalks/dtalks/news/service/NewsServiceImpl.java
1. Crawling 정보를 DB에 저장하지 않고 불러오던것 -> DB 저장 api, DB 조회 api 로 수정
2. get /news -> 저장된 News중 최신 20개 list로 받아옴
3. post /news -> BLOTER 사이트의 IT 기업 new 기사(제목, 내용, 작성자, 날짜, 이미지 주소, 링크) 반환
=> fix:Crawling해서 DB에 저장, Crawl 정보 DB에서 조회

src/main/java/com/dtalks/dtalks/board/post/controller/PostController.java, src/main/java/com/dtalks/dtalks/board/post/dto/PostDto.java, src/main/java/com/dtalks/dtalks/board/post/dto/PostRequestDto.java, src/main/java/com/dtalks/dtalks/board/post/service/PostService.java, src/main/java/com/dtalks/dtalks/board/post/service/PostServiceImpl.java
1. 게시글 작성, 수정 시 document에 s3 path 추가
2. 게시글 수정, 삭제 시 s3에서 이미지 삭제 필요할 때 url이 아닌 path를 이용하도록 수정
3. 게시글 작성, 수정 시에 데이터 매핑 방법을 RequestPart에서 **modelAttribute로 변경** (multipart/form-data 지정하고 json데이터에 따로 application/json 넣어주는 방식이 아닌 **multipart/form-data만 content-type에 넣어주면 됨**)
=> fix:post s3에서 이미지 삭제 path 이용, 게시글 작성 or 수정 시 modelAttribute이용

src/main/java/com/dtalks/dtalks/board/comment/dto/CommentInfoDto.java, src/main/java/com/dtalks/dtalks/board/comment/dto/CommentRequestDto.java, src/main/java/com/dtalks/dtalks/board/comment/dto/UserCommentDto.java, src/main/java/com/dtalks/dtalks/board/comment/entity/Comment.java, src/main/java/com/dtalks/dtalks/board/comment/repository/CommentRepository.java, src/main/java/com/dtalks/dtalks/board/comment/service/CommentServiceImpl.java, src/main/java/com/dtalks/dtalks/board/post/dto/PostDto.java, src/main/java/com/dtalks/dtalks/qna/answer/dto/AnswerResponseDto.java, src/main/java/com/dtalks/dtalks/qna/question/dto/QuestionResponseDto.java, src/main/java/com/dtalks/dtalks/user/dto/UserSimpleDto.java
1. 댓글, 질문, 답변 응답 dto에 작성일, 수정일 추가
2. 사용자 닉네임과 이미지만 응답 dto에서 공통적으로 쓰일 것으로 예상해 관련 내용만 가지고 있는 UserSimpleDto 파일 생성
3. 게시글, 댓글 응답 dto에서 사용자 관련 내용은 userInfo로 전달(nickname, profile)
4. 댓글 비밀 설정 수정 (entity, dto에서 boolean인 필드 isSecret, isRemoved -> secret, removed로 변경) **db 수정 필요**
=> fix: 게시글, 댓글 응답 dto에 사용자 이미지 추가, 댓글 질문 답변에 생성일 추가

build.gradle, src/main/java/com/dtalks/dtalks/studyroom/config/WebSocketConfiguration.java, src/main/java/com/dtalks/dtalks/studyroom/controller/ChatController.java, src/main/java/com/dtalks/dtalks/studyroom/dto/ChatMessageDto.java, src/main/java/com/dtalks/dtalks/studyroom/dto/ChatMessageRequestDto.java, src/main/java/com/dtalks/dtalks/studyroom/dto/ChatRoomDto.java, src/main/java/com/dtalks/dtalks/studyroom/entity/ChatMessage.java, src/main/java/com/dtalks/dtalks/studyroom/entity/ChatRoom.java, src/main/java/com/dtalks/dtalks/studyroom/repository/ChatMessageRepository.java, src/main/java/com/dtalks/dtalks/studyroom/repository/ChatRoomRepository.java, src/main/java/com/dtalks/dtalks/studyroom/service/ChatService.java, src/main/java/com/dtalks/dtalks/studyroom/service/ChatServiceImpl.java, src/main/java/com/dtalks/dtalks/studyroom/service/StudyRoomServiceImpl.java
- 실시간 채팅 기능을 위해 stomp 프로토콜을 사용하였고, pub/sub 방식을 사용하였습니다.
- 스터디룸 생성시 자동으로 채팅방 생성
- 웹소켓 연결 /ws/chat
- 채팅 입력시 /pub, 구독자들에게 새로운 채팅 전달시 /sub
- 채팅방의 모든 채팅 가져오기, page로 가져오고 최근순으로 가져옴, 페이지당 100개가 기본
- 채팅방 - 스터디룸은 1대1, 채팅방 - 채팅은 1대n, 유저 - 채팅은 1대n.
- 스터디룸쪽 db 삭제 필요
=> feat: 채팅 기능 추가

src/main/java/com/dtalks/dtalks/alarm/service/AlarmServiceImpl.java, src/main/java/com/dtalks/dtalks/board/post/controller/PostController.java, src/main/java/com/dtalks/dtalks/board/post/dto/PutRequestDto.java, src/main/java/com/dtalks/dtalks/board/post/service/PostService.java, src/main/java/com/dtalks/dtalks/board/post/service/PostServiceImpl.java
s3 url로만 프론트에서 넘겨줄 수 있어서 남아있는 게시글 이미지는 String으로 넘어올 수 있고 새로운 이미지만 파일 형식으로 올 수 있음.
그거에 맞춰서 새로운 dto 생성.
+알람 transactional 추가
=> fix: 게시글 수정 기존 이미지 처리 방법 변경

src/main/java/com/dtalks/dtalks/user/controller/UserController.java, src/main/java/com/dtalks/dtalks/user/dto/UserSimplePasswordDto.java, src/main/java/com/dtalks/dtalks/user/entity/User.java, src/main/java/com/dtalks/dtalks/user/service/UserService.java, src/main/java/com/dtalks/dtalks/user/service/UserServiceImpl.java
- 회원 탈퇴시 이메일, 아이디 null로 변경, isActive false로 변경, 비밀번호 무작위값으로 변경, nickname (알수없음)으로 변경.
- isActve false이면 로그인 못하도록 수정
=> feat: 유저 회원 탈퇴 api

src/main/java/com/dtalks/dtalks/user/controller/SignController.java, src/main/java/com/dtalks/dtalks/user/controller/UserController.java, src/main/java/com/dtalks/dtalks/user/dto/DuplicateResponseDto.java, src/main/java/com/dtalks/dtalks/user/dto/SignInResponseDto.java, src/main/java/com/dtalks/dtalks/user/service/TokenServiceImpl.java, src/main/java/com/dtalks/dtalks/user/service/UserService.java, src/main/java/com/dtalks/dtalks/user/service/UserServiceImpl.java, src/test/java/com/dtalks/dtalks/user/service/UserServiceImplTest.java
- 회원가입 리턴값 void로 변경
- 로그인, oauth 회원가입 리턴값 access, refresh 토큰만 주도록 변경
- 리프레시 토큰이용한 재발급 리턴값 access, refresh 토큰만 주도록 변경
- 유저아이디, 닉네임, 비밀번호, 이메일 변경시 access, refresh 토큰만 주도록 변경
- 프로필 이미지 업로드시 기존 document 삭제후 새로 생성하도록 변경
- test 코드 임시로 전체 주석처리
=> fix: 유저 서비스 리팩토링

src/main/java/com/dtalks/dtalks/board/comment/controller/CommentController.java, src/main/java/com/dtalks/dtalks/board/comment/service/CommentService.java, src/main/java/com/dtalks/dtalks/board/comment/service/CommentServiceImpl.java, src/main/java/com/dtalks/dtalks/board/post/controller/PostController.java, src/main/java/com/dtalks/dtalks/board/post/entity/Post.java, src/main/java/com/dtalks/dtalks/board/post/service/FavoritePostService.java, src/main/java/com/dtalks/dtalks/board/post/service/FavoritePostServiceImpl.java, src/main/java/com/dtalks/dtalks/board/post/service/PostService.java, src/main/java/com/dtalks/dtalks/board/post/service/PostServiceImpl.java
게시글, 댓글 리스트 userId -> nickname으로 가져오게 수정
게시글 불러올때 작성자 닉네임, 이미지 가져오게 수정한 후, user가 무조건 쓰이는데 즐겨찾기 리스트는 querydsl로 작성해 작성자 정보가 lazy loading이면 불러올 수 없었음. 어차피 작성자 정보가 계속 쓰이므로 fetchtype lazy 삭제
=> Fix:닉네임으로 불러오도록 수정, post의 user eager로 변경

src/main/java/com/dtalks/dtalks/admin/report/entity/Report.java, src/main/java/com/dtalks/dtalks/report/controller/ReportController.java, src/main/java/com/dtalks/dtalks/report/dto/ReportDetailDto.java, src/main/java/com/dtalks/dtalks/report/dto/ReportDetailRequestDto.java, src/main/java/com/dtalks/dtalks/report/entity/Report.java, src/main/java/com/dtalks/dtalks/report/entity/ReportTimeEntity.java, src/main/java/com/dtalks/dtalks/report/entity/ReportedUser.java, src/main/java/com/dtalks/dtalks/report/enums/ReportType.java, src/main/java/com/dtalks/dtalks/report/enums/ResultType.java, src/main/java/com/dtalks/dtalks/report/repository/ReportRepository.java, src/main/java/com/dtalks/dtalks/report/repository/ReportedUserRepository.java, src/main/java/com/dtalks/dtalks/report/service/ReportUserService.java, src/main/java/com/dtalks/dtalks/report/service/ReportUserServiceImpl.java, src/main/java/com/dtalks/dtalks/user/entity/User.java, src/main/java/com/dtalks/dtalks/user/enums/ActiveStatus.java, src/main/java/com/dtalks/dtalks/user/service/UserServiceImpl.java
사용하지 않던 status를 ActiveStatus enum 으로 수정. 회원가입 시 활동을 뜻하는 ACTIVE로 되고 탈퇴 시에는 QUIT, 관리자에 의해 정지될 경우 SUSPENSION, 계정이 아예 잠길 경우(금지)에는 BAN으로 설정
=> feat: User status를 활동 타입으로 수정

src/main/java/com/dtalks/dtalks/user/dto/UserResponseDto.java, src/main/java/com/dtalks/dtalks/user/entity/User.java
lazy로 설정시 could not initialize proxy - no Session 에러가 발생합니다.
서비스 단에서 데이터를 필요로 하지 않아 컨트롤러에서 리턴 할 때 fetch lazy가 실행되어 영속 컨텍스트가 존재하지 않아 에러가 발생하는 것으로 추측됩니다. 로그 출력등의 코드를 넣어 강제로 사용하도록 하게 할 경우 쿼리가 수행되지만, 매번 이렇게 하면 쓸모없는 로그가 너무 많이 찍힌다고 생각했고 마땅히 더 좋은 방법이 생각나지 않아 우선 eager로 바꾸어 주었습니다.
=> fix: 유저 스킬, 역할 fetch lazy 원하는 시점에 쿼리 하도록 변경

src/main/java/com/dtalks/dtalks/studyroom/entity/ChatRoom.java, src/main/java/com/dtalks/dtalks/studyroom/service/StudyRoomServiceImpl.java
스터디룸 삭제시 스터디룸과 채팅방이 1대1 단방향으로 연결되어 있어 채팅방을 삭제해야 스터디룸이 같이 삭제되므로 그렇게 변경하였습니다.
채팅방 삭제시 채팅이 삭제되어야 하는데 다대일 단방향으로 연결되어 있어 이를 양방향으로 바꾼뒤 고아가 될경우 삭제하도록 처리하였습니다.
=> fix: 스터디룸 삭제시 채팅방, 채팅 삭제

src/main/java/com/dtalks/dtalks/base/validation/EnumValidator.java, src/main/java/com/dtalks/dtalks/base/validation/ValidEnum.java, src/main/java/com/dtalks/dtalks/report/dto/ReportDetailRequestDto.java
postman에서는 에러가 안 떠서 몰랐는데 스웨거에서 reportType에 아무것도 안 들어와서 에러가 발생. NotBlank와 같은 타입은 원시타입만 validation 가능.
=> Fix: enum validation 수정

src/main/java/com/dtalks/dtalks/user/config/JwtAuthenticationFilter.java, src/main/java/com/dtalks/dtalks/user/controller/UserController.java, src/main/java/com/dtalks/dtalks/user/service/TokenServiceImpl.java, src/main/java/com/dtalks/dtalks/user/service/UserService.java, src/main/java/com/dtalks/dtalks/user/service/UserServiceImpl.java
- SecurityUtil.getUser()와 같은 사용으로 컨텍스트 홀더에서 사용자 인증 정보를 가져올 때 계정 정지 된 사용자면 정보를 가져오지 못 하는 에러 발생.
1. SecurityUtil을 사용하는 GET 메소드 파악, 필터 리스트 수정
2. doFilterInternal에서 컨텍스트 홀더에 사용자 인증 정보 저장 후 GET요청이 아닐 때 에러 발생하도록 수정
- 사용자 비공개 조회를 사용자 로그인 아이디에서 닉네임으로 수정
=> fix: 계정 정지 사용자 인증 변경, filter 리스트 변경, 사용자 비공개 조회 닉네임으로 수정
